# Generated by Django 5.0.6 on 2026-05-05 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filiere', models.CharField(max_length=100)),
                ('langue', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=20)),
                ('matiere', models.CharField(max_length=100)),
                ('type_document', models.CharField(choices=[('cours', 'Cours'), ('national', 'Examen National'), ('rattrapage', 'Rattrapage')], max_length=20)),
                ('fichier', models.FileField(upload_to='pdfs/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('telechargements', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'document')},
            },
        ),
    ]
